### ISSUE TITLE
Opening in current folder not working

### ISSUE THREAD

**Issue by sesselastronaut** [ganiserb/thunar-terminal#1]
I'm having trouble with this script using Openbox and Thunar 1.6.3 - the console opens fine but unfortunately only in the home directory, no matter which directory I'm calling the script in thunar. Is there a way to debug? Thanks in advance

**Comment by ganiserb** [comment]
@sesselastronaut Sorry I took so long to answer. I don't know why the GitHub notifications were disabled. I'll take a look at it. Thanks for the feedback.

**Comment by ganiserb** [comment]
I'm closing this because I no longer use Thunar.
